/*
 *  config.h
 *  Ultramix
 *
 *  LAME's build configuration, written by hand instead of generated by
 *  autoconf: there is exactly one target - macOS on Apple Silicon, clang -
 *  so there is nothing to probe for. Everything below is a fact of that
 *  platform, and everything left undefined is off on purpose:
 *
 *  - HAVE_MPGLIB, HAVE_MPG123, DECODE_ON_THE_FLY: the MP3 *decoder*.
 *    Ultramix only encodes; decoding goes through AVFoundation.
 *  - HAVE_NASM, HAVE_XMMINTRIN_H: the x86 assembly and SSE paths. Their
 *    sources (i386/, vector/xmm_quantize_sub.c) are not in the target.
 *  - TAKEHIRO_IEEE754_HACK: a quantiser shortcut that reinterprets float
 *    bits, written for x86. The portable code path is the one to trust on
 *    ARM.
 *
 *  The upstream template is lame-master/config.h.in.
 */

#ifndef LAME_CONFIG_H
#define LAME_CONFIG_H

#define STDC_HEADERS 1
#define HAVE_ERRNO_H 1
#define HAVE_FCNTL_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_LIMITS_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define HAVE_STRTOL 1

/* The fixed-width integers come from <stdint.h>; saying so stops LAME
   from typedef-ing its own. */
#include <stdint.h>
#define HAVE_INT8_T 1
#define HAVE_INT16_T 1
#define HAVE_INT32_T 1
#define HAVE_INT64_T 1
#define HAVE_UINT8_T 1
#define HAVE_UINT16_T 1
#define HAVE_UINT32_T 1
#define HAVE_UINT64_T 1

/* No system header provides these; LAME expects the configuration to. */
typedef float ieee754_float32_t;
typedef double ieee754_float64_t;
typedef long double ieee854_float80_t;
#define HAVE_IEEE754_FLOAT32_T 1
#define HAVE_IEEE754_FLOAT64_T 1
#define HAVE_IEEE854_FLOAT80_T 1

/* arm64, LP64. long double is 8 bytes on Apple Silicon, not 16. */
#define SIZEOF_SHORT 2
#define SIZEOF_UNSIGNED_SHORT 2
#define SIZEOF_INT 4
#define SIZEOF_UNSIGNED_INT 4
#define SIZEOF_LONG 8
#define SIZEOF_UNSIGNED_LONG 8
#define SIZEOF_LONG_LONG 8
#define SIZEOF_UNSIGNED_LONG_LONG 8
#define SIZEOF_FLOAT 4
#define SIZEOF_DOUBLE 8
#define SIZEOF_LONG_DOUBLE 8

#define PACKAGE "lame"
#define VERSION "3.100"

#endif /* LAME_CONFIG_H */
